// Multi-query attention for one query token (decoding) -- v6: subgroup broadcasts instead of repeated loads.
#define H 8
#define DK 576
#define DV 512
#define WG 64
#define CHMAX 256
__attribute__((reqd_work_group_size(WG, 1, 1))) __attribute__((intel_reqd_sub_group_size(8)))
__kernel void attn_chunk(__global const half * K, ulong k_stride, __global const half * V, ulong v_stride,
                         __global const float * Q, ulong q_stride, __global const half * mask, float scale, int n_kv,
                         __global float * part, int ch) {
    __local float P[H][CHMAX];
    __local float Ml[H], Sl[H];
    const int c = get_group_id(0), lid = get_local_id(0), r0 = c * ch;
    const int sg = get_sub_group_id(), lane = get_sub_group_local_id();
    // 1) scores: lane = one cached row, all heads; the query comes by block read + register broadcast
    for (int j = 0; j < ch / WG; j++) {
        const int rl = j * WG + lid, r = r0 + rl;
        const bool live = r < n_kv;
        __global const half * kr = K + (size_t) (live ? r : 0) * k_stride;
        float acc[H];
        for (int h = 0; h < H; h++) acc[h] = 0.0f;
        for (int t = 0; t < DK / 64; t++) {
            float8 q[H];
            for (int h = 0; h < H; h++) q[h] = as_float8(intel_sub_group_block_read8((__global const uint *) (Q + h * q_stride + t * 64)));
            float8 kv;
            kv = vload_half8(0, kr + t * 64 + 0);
            acc[0] = fma(kv.s0, sub_group_broadcast(q[0].s0, 0), acc[0]); acc[1] = fma(kv.s0, sub_group_broadcast(q[1].s0, 0), acc[1]); acc[2] = fma(kv.s0, sub_group_broadcast(q[2].s0, 0), acc[2]); acc[3] = fma(kv.s0, sub_group_broadcast(q[3].s0, 0), acc[3]); acc[4] = fma(kv.s0, sub_group_broadcast(q[4].s0, 0), acc[4]); acc[5] = fma(kv.s0, sub_group_broadcast(q[5].s0, 0), acc[5]); acc[6] = fma(kv.s0, sub_group_broadcast(q[6].s0, 0), acc[6]); acc[7] = fma(kv.s0, sub_group_broadcast(q[7].s0, 0), acc[7]);
            acc[0] = fma(kv.s1, sub_group_broadcast(q[0].s0, 1), acc[0]); acc[1] = fma(kv.s1, sub_group_broadcast(q[1].s0, 1), acc[1]); acc[2] = fma(kv.s1, sub_group_broadcast(q[2].s0, 1), acc[2]); acc[3] = fma(kv.s1, sub_group_broadcast(q[3].s0, 1), acc[3]); acc[4] = fma(kv.s1, sub_group_broadcast(q[4].s0, 1), acc[4]); acc[5] = fma(kv.s1, sub_group_broadcast(q[5].s0, 1), acc[5]); acc[6] = fma(kv.s1, sub_group_broadcast(q[6].s0, 1), acc[6]); acc[7] = fma(kv.s1, sub_group_broadcast(q[7].s0, 1), acc[7]);
            acc[0] = fma(kv.s2, sub_group_broadcast(q[0].s0, 2), acc[0]); acc[1] = fma(kv.s2, sub_group_broadcast(q[1].s0, 2), acc[1]); acc[2] = fma(kv.s2, sub_group_broadcast(q[2].s0, 2), acc[2]); acc[3] = fma(kv.s2, sub_group_broadcast(q[3].s0, 2), acc[3]); acc[4] = fma(kv.s2, sub_group_broadcast(q[4].s0, 2), acc[4]); acc[5] = fma(kv.s2, sub_group_broadcast(q[5].s0, 2), acc[5]); acc[6] = fma(kv.s2, sub_group_broadcast(q[6].s0, 2), acc[6]); acc[7] = fma(kv.s2, sub_group_broadcast(q[7].s0, 2), acc[7]);
            acc[0] = fma(kv.s3, sub_group_broadcast(q[0].s0, 3), acc[0]); acc[1] = fma(kv.s3, sub_group_broadcast(q[1].s0, 3), acc[1]); acc[2] = fma(kv.s3, sub_group_broadcast(q[2].s0, 3), acc[2]); acc[3] = fma(kv.s3, sub_group_broadcast(q[3].s0, 3), acc[3]); acc[4] = fma(kv.s3, sub_group_broadcast(q[4].s0, 3), acc[4]); acc[5] = fma(kv.s3, sub_group_broadcast(q[5].s0, 3), acc[5]); acc[6] = fma(kv.s3, sub_group_broadcast(q[6].s0, 3), acc[6]); acc[7] = fma(kv.s3, sub_group_broadcast(q[7].s0, 3), acc[7]);
            acc[0] = fma(kv.s4, sub_group_broadcast(q[0].s0, 4), acc[0]); acc[1] = fma(kv.s4, sub_group_broadcast(q[1].s0, 4), acc[1]); acc[2] = fma(kv.s4, sub_group_broadcast(q[2].s0, 4), acc[2]); acc[3] = fma(kv.s4, sub_group_broadcast(q[3].s0, 4), acc[3]); acc[4] = fma(kv.s4, sub_group_broadcast(q[4].s0, 4), acc[4]); acc[5] = fma(kv.s4, sub_group_broadcast(q[5].s0, 4), acc[5]); acc[6] = fma(kv.s4, sub_group_broadcast(q[6].s0, 4), acc[6]); acc[7] = fma(kv.s4, sub_group_broadcast(q[7].s0, 4), acc[7]);
            acc[0] = fma(kv.s5, sub_group_broadcast(q[0].s0, 5), acc[0]); acc[1] = fma(kv.s5, sub_group_broadcast(q[1].s0, 5), acc[1]); acc[2] = fma(kv.s5, sub_group_broadcast(q[2].s0, 5), acc[2]); acc[3] = fma(kv.s5, sub_group_broadcast(q[3].s0, 5), acc[3]); acc[4] = fma(kv.s5, sub_group_broadcast(q[4].s0, 5), acc[4]); acc[5] = fma(kv.s5, sub_group_broadcast(q[5].s0, 5), acc[5]); acc[6] = fma(kv.s5, sub_group_broadcast(q[6].s0, 5), acc[6]); acc[7] = fma(kv.s5, sub_group_broadcast(q[7].s0, 5), acc[7]);
            acc[0] = fma(kv.s6, sub_group_broadcast(q[0].s0, 6), acc[0]); acc[1] = fma(kv.s6, sub_group_broadcast(q[1].s0, 6), acc[1]); acc[2] = fma(kv.s6, sub_group_broadcast(q[2].s0, 6), acc[2]); acc[3] = fma(kv.s6, sub_group_broadcast(q[3].s0, 6), acc[3]); acc[4] = fma(kv.s6, sub_group_broadcast(q[4].s0, 6), acc[4]); acc[5] = fma(kv.s6, sub_group_broadcast(q[5].s0, 6), acc[5]); acc[6] = fma(kv.s6, sub_group_broadcast(q[6].s0, 6), acc[6]); acc[7] = fma(kv.s6, sub_group_broadcast(q[7].s0, 6), acc[7]);
            acc[0] = fma(kv.s7, sub_group_broadcast(q[0].s0, 7), acc[0]); acc[1] = fma(kv.s7, sub_group_broadcast(q[1].s0, 7), acc[1]); acc[2] = fma(kv.s7, sub_group_broadcast(q[2].s0, 7), acc[2]); acc[3] = fma(kv.s7, sub_group_broadcast(q[3].s0, 7), acc[3]); acc[4] = fma(kv.s7, sub_group_broadcast(q[4].s0, 7), acc[4]); acc[5] = fma(kv.s7, sub_group_broadcast(q[5].s0, 7), acc[5]); acc[6] = fma(kv.s7, sub_group_broadcast(q[6].s0, 7), acc[6]); acc[7] = fma(kv.s7, sub_group_broadcast(q[7].s0, 7), acc[7]);
            kv = vload_half8(0, kr + t * 64 + 8);
            acc[0] = fma(kv.s0, sub_group_broadcast(q[0].s1, 0), acc[0]); acc[1] = fma(kv.s0, sub_group_broadcast(q[1].s1, 0), acc[1]); acc[2] = fma(kv.s0, sub_group_broadcast(q[2].s1, 0), acc[2]); acc[3] = fma(kv.s0, sub_group_broadcast(q[3].s1, 0), acc[3]); acc[4] = fma(kv.s0, sub_group_broadcast(q[4].s1, 0), acc[4]); acc[5] = fma(kv.s0, sub_group_broadcast(q[5].s1, 0), acc[5]); acc[6] = fma(kv.s0, sub_group_broadcast(q[6].s1, 0), acc[6]); acc[7] = fma(kv.s0, sub_group_broadcast(q[7].s1, 0), acc[7]);
            acc[0] = fma(kv.s1, sub_group_broadcast(q[0].s1, 1), acc[0]); acc[1] = fma(kv.s1, sub_group_broadcast(q[1].s1, 1), acc[1]); acc[2] = fma(kv.s1, sub_group_broadcast(q[2].s1, 1), acc[2]); acc[3] = fma(kv.s1, sub_group_broadcast(q[3].s1, 1), acc[3]); acc[4] = fma(kv.s1, sub_group_broadcast(q[4].s1, 1), acc[4]); acc[5] = fma(kv.s1, sub_group_broadcast(q[5].s1, 1), acc[5]); acc[6] = fma(kv.s1, sub_group_broadcast(q[6].s1, 1), acc[6]); acc[7] = fma(kv.s1, sub_group_broadcast(q[7].s1, 1), acc[7]);
            acc[0] = fma(kv.s2, sub_group_broadcast(q[0].s1, 2), acc[0]); acc[1] = fma(kv.s2, sub_group_broadcast(q[1].s1, 2), acc[1]); acc[2] = fma(kv.s2, sub_group_broadcast(q[2].s1, 2), acc[2]); acc[3] = fma(kv.s2, sub_group_broadcast(q[3].s1, 2), acc[3]); acc[4] = fma(kv.s2, sub_group_broadcast(q[4].s1, 2), acc[4]); acc[5] = fma(kv.s2, sub_group_broadcast(q[5].s1, 2), acc[5]); acc[6] = fma(kv.s2, sub_group_broadcast(q[6].s1, 2), acc[6]); acc[7] = fma(kv.s2, sub_group_broadcast(q[7].s1, 2), acc[7]);
            acc[0] = fma(kv.s3, sub_group_broadcast(q[0].s1, 3), acc[0]); acc[1] = fma(kv.s3, sub_group_broadcast(q[1].s1, 3), acc[1]); acc[2] = fma(kv.s3, sub_group_broadcast(q[2].s1, 3), acc[2]); acc[3] = fma(kv.s3, sub_group_broadcast(q[3].s1, 3), acc[3]); acc[4] = fma(kv.s3, sub_group_broadcast(q[4].s1, 3), acc[4]); acc[5] = fma(kv.s3, sub_group_broadcast(q[5].s1, 3), acc[5]); acc[6] = fma(kv.s3, sub_group_broadcast(q[6].s1, 3), acc[6]); acc[7] = fma(kv.s3, sub_group_broadcast(q[7].s1, 3), acc[7]);
            acc[0] = fma(kv.s4, sub_group_broadcast(q[0].s1, 4), acc[0]); acc[1] = fma(kv.s4, sub_group_broadcast(q[1].s1, 4), acc[1]); acc[2] = fma(kv.s4, sub_group_broadcast(q[2].s1, 4), acc[2]); acc[3] = fma(kv.s4, sub_group_broadcast(q[3].s1, 4), acc[3]); acc[4] = fma(kv.s4, sub_group_broadcast(q[4].s1, 4), acc[4]); acc[5] = fma(kv.s4, sub_group_broadcast(q[5].s1, 4), acc[5]); acc[6] = fma(kv.s4, sub_group_broadcast(q[6].s1, 4), acc[6]); acc[7] = fma(kv.s4, sub_group_broadcast(q[7].s1, 4), acc[7]);
            acc[0] = fma(kv.s5, sub_group_broadcast(q[0].s1, 5), acc[0]); acc[1] = fma(kv.s5, sub_group_broadcast(q[1].s1, 5), acc[1]); acc[2] = fma(kv.s5, sub_group_broadcast(q[2].s1, 5), acc[2]); acc[3] = fma(kv.s5, sub_group_broadcast(q[3].s1, 5), acc[3]); acc[4] = fma(kv.s5, sub_group_broadcast(q[4].s1, 5), acc[4]); acc[5] = fma(kv.s5, sub_group_broadcast(q[5].s1, 5), acc[5]); acc[6] = fma(kv.s5, sub_group_broadcast(q[6].s1, 5), acc[6]); acc[7] = fma(kv.s5, sub_group_broadcast(q[7].s1, 5), acc[7]);
            acc[0] = fma(kv.s6, sub_group_broadcast(q[0].s1, 6), acc[0]); acc[1] = fma(kv.s6, sub_group_broadcast(q[1].s1, 6), acc[1]); acc[2] = fma(kv.s6, sub_group_broadcast(q[2].s1, 6), acc[2]); acc[3] = fma(kv.s6, sub_group_broadcast(q[3].s1, 6), acc[3]); acc[4] = fma(kv.s6, sub_group_broadcast(q[4].s1, 6), acc[4]); acc[5] = fma(kv.s6, sub_group_broadcast(q[5].s1, 6), acc[5]); acc[6] = fma(kv.s6, sub_group_broadcast(q[6].s1, 6), acc[6]); acc[7] = fma(kv.s6, sub_group_broadcast(q[7].s1, 6), acc[7]);
            acc[0] = fma(kv.s7, sub_group_broadcast(q[0].s1, 7), acc[0]); acc[1] = fma(kv.s7, sub_group_broadcast(q[1].s1, 7), acc[1]); acc[2] = fma(kv.s7, sub_group_broadcast(q[2].s1, 7), acc[2]); acc[3] = fma(kv.s7, sub_group_broadcast(q[3].s1, 7), acc[3]); acc[4] = fma(kv.s7, sub_group_broadcast(q[4].s1, 7), acc[4]); acc[5] = fma(kv.s7, sub_group_broadcast(q[5].s1, 7), acc[5]); acc[6] = fma(kv.s7, sub_group_broadcast(q[6].s1, 7), acc[6]); acc[7] = fma(kv.s7, sub_group_broadcast(q[7].s1, 7), acc[7]);
            kv = vload_half8(0, kr + t * 64 + 16);
            acc[0] = fma(kv.s0, sub_group_broadcast(q[0].s2, 0), acc[0]); acc[1] = fma(kv.s0, sub_group_broadcast(q[1].s2, 0), acc[1]); acc[2] = fma(kv.s0, sub_group_broadcast(q[2].s2, 0), acc[2]); acc[3] = fma(kv.s0, sub_group_broadcast(q[3].s2, 0), acc[3]); acc[4] = fma(kv.s0, sub_group_broadcast(q[4].s2, 0), acc[4]); acc[5] = fma(kv.s0, sub_group_broadcast(q[5].s2, 0), acc[5]); acc[6] = fma(kv.s0, sub_group_broadcast(q[6].s2, 0), acc[6]); acc[7] = fma(kv.s0, sub_group_broadcast(q[7].s2, 0), acc[7]);
            acc[0] = fma(kv.s1, sub_group_broadcast(q[0].s2, 1), acc[0]); acc[1] = fma(kv.s1, sub_group_broadcast(q[1].s2, 1), acc[1]); acc[2] = fma(kv.s1, sub_group_broadcast(q[2].s2, 1), acc[2]); acc[3] = fma(kv.s1, sub_group_broadcast(q[3].s2, 1), acc[3]); acc[4] = fma(kv.s1, sub_group_broadcast(q[4].s2, 1), acc[4]); acc[5] = fma(kv.s1, sub_group_broadcast(q[5].s2, 1), acc[5]); acc[6] = fma(kv.s1, sub_group_broadcast(q[6].s2, 1), acc[6]); acc[7] = fma(kv.s1, sub_group_broadcast(q[7].s2, 1), acc[7]);
            acc[0] = fma(kv.s2, sub_group_broadcast(q[0].s2, 2), acc[0]); acc[1] = fma(kv.s2, sub_group_broadcast(q[1].s2, 2), acc[1]); acc[2] = fma(kv.s2, sub_group_broadcast(q[2].s2, 2), acc[2]); acc[3] = fma(kv.s2, sub_group_broadcast(q[3].s2, 2), acc[3]); acc[4] = fma(kv.s2, sub_group_broadcast(q[4].s2, 2), acc[4]); acc[5] = fma(kv.s2, sub_group_broadcast(q[5].s2, 2), acc[5]); acc[6] = fma(kv.s2, sub_group_broadcast(q[6].s2, 2), acc[6]); acc[7] = fma(kv.s2, sub_group_broadcast(q[7].s2, 2), acc[7]);
            acc[0] = fma(kv.s3, sub_group_broadcast(q[0].s2, 3), acc[0]); acc[1] = fma(kv.s3, sub_group_broadcast(q[1].s2, 3), acc[1]); acc[2] = fma(kv.s3, sub_group_broadcast(q[2].s2, 3), acc[2]); acc[3] = fma(kv.s3, sub_group_broadcast(q[3].s2, 3), acc[3]); acc[4] = fma(kv.s3, sub_group_broadcast(q[4].s2, 3), acc[4]); acc[5] = fma(kv.s3, sub_group_broadcast(q[5].s2, 3), acc[5]); acc[6] = fma(kv.s3, sub_group_broadcast(q[6].s2, 3), acc[6]); acc[7] = fma(kv.s3, sub_group_broadcast(q[7].s2, 3), acc[7]);
            acc[0] = fma(kv.s4, sub_group_broadcast(q[0].s2, 4), acc[0]); acc[1] = fma(kv.s4, sub_group_broadcast(q[1].s2, 4), acc[1]); acc[2] = fma(kv.s4, sub_group_broadcast(q[2].s2, 4), acc[2]); acc[3] = fma(kv.s4, sub_group_broadcast(q[3].s2, 4), acc[3]); acc[4] = fma(kv.s4, sub_group_broadcast(q[4].s2, 4), acc[4]); acc[5] = fma(kv.s4, sub_group_broadcast(q[5].s2, 4), acc[5]); acc[6] = fma(kv.s4, sub_group_broadcast(q[6].s2, 4), acc[6]); acc[7] = fma(kv.s4, sub_group_broadcast(q[7].s2, 4), acc[7]);
            acc[0] = fma(kv.s5, sub_group_broadcast(q[0].s2, 5), acc[0]); acc[1] = fma(kv.s5, sub_group_broadcast(q[1].s2, 5), acc[1]); acc[2] = fma(kv.s5, sub_group_broadcast(q[2].s2, 5), acc[2]); acc[3] = fma(kv.s5, sub_group_broadcast(q[3].s2, 5), acc[3]); acc[4] = fma(kv.s5, sub_group_broadcast(q[4].s2, 5), acc[4]); acc[5] = fma(kv.s5, sub_group_broadcast(q[5].s2, 5), acc[5]); acc[6] = fma(kv.s5, sub_group_broadcast(q[6].s2, 5), acc[6]); acc[7] = fma(kv.s5, sub_group_broadcast(q[7].s2, 5), acc[7]);
            acc[0] = fma(kv.s6, sub_group_broadcast(q[0].s2, 6), acc[0]); acc[1] = fma(kv.s6, sub_group_broadcast(q[1].s2, 6), acc[1]); acc[2] = fma(kv.s6, sub_group_broadcast(q[2].s2, 6), acc[2]); acc[3] = fma(kv.s6, sub_group_broadcast(q[3].s2, 6), acc[3]); acc[4] = fma(kv.s6, sub_group_broadcast(q[4].s2, 6), acc[4]); acc[5] = fma(kv.s6, sub_group_broadcast(q[5].s2, 6), acc[5]); acc[6] = fma(kv.s6, sub_group_broadcast(q[6].s2, 6), acc[6]); acc[7] = fma(kv.s6, sub_group_broadcast(q[7].s2, 6), acc[7]);
            acc[0] = fma(kv.s7, sub_group_broadcast(q[0].s2, 7), acc[0]); acc[1] = fma(kv.s7, sub_group_broadcast(q[1].s2, 7), acc[1]); acc[2] = fma(kv.s7, sub_group_broadcast(q[2].s2, 7), acc[2]); acc[3] = fma(kv.s7, sub_group_broadcast(q[3].s2, 7), acc[3]); acc[4] = fma(kv.s7, sub_group_broadcast(q[4].s2, 7), acc[4]); acc[5] = fma(kv.s7, sub_group_broadcast(q[5].s2, 7), acc[5]); acc[6] = fma(kv.s7, sub_group_broadcast(q[6].s2, 7), acc[6]); acc[7] = fma(kv.s7, sub_group_broadcast(q[7].s2, 7), acc[7]);
            kv = vload_half8(0, kr + t * 64 + 24);
            acc[0] = fma(kv.s0, sub_group_broadcast(q[0].s3, 0), acc[0]); acc[1] = fma(kv.s0, sub_group_broadcast(q[1].s3, 0), acc[1]); acc[2] = fma(kv.s0, sub_group_broadcast(q[2].s3, 0), acc[2]); acc[3] = fma(kv.s0, sub_group_broadcast(q[3].s3, 0), acc[3]); acc[4] = fma(kv.s0, sub_group_broadcast(q[4].s3, 0), acc[4]); acc[5] = fma(kv.s0, sub_group_broadcast(q[5].s3, 0), acc[5]); acc[6] = fma(kv.s0, sub_group_broadcast(q[6].s3, 0), acc[6]); acc[7] = fma(kv.s0, sub_group_broadcast(q[7].s3, 0), acc[7]);
            acc[0] = fma(kv.s1, sub_group_broadcast(q[0].s3, 1), acc[0]); acc[1] = fma(kv.s1, sub_group_broadcast(q[1].s3, 1), acc[1]); acc[2] = fma(kv.s1, sub_group_broadcast(q[2].s3, 1), acc[2]); acc[3] = fma(kv.s1, sub_group_broadcast(q[3].s3, 1), acc[3]); acc[4] = fma(kv.s1, sub_group_broadcast(q[4].s3, 1), acc[4]); acc[5] = fma(kv.s1, sub_group_broadcast(q[5].s3, 1), acc[5]); acc[6] = fma(kv.s1, sub_group_broadcast(q[6].s3, 1), acc[6]); acc[7] = fma(kv.s1, sub_group_broadcast(q[7].s3, 1), acc[7]);
            acc[0] = fma(kv.s2, sub_group_broadcast(q[0].s3, 2), acc[0]); acc[1] = fma(kv.s2, sub_group_broadcast(q[1].s3, 2), acc[1]); acc[2] = fma(kv.s2, sub_group_broadcast(q[2].s3, 2), acc[2]); acc[3] = fma(kv.s2, sub_group_broadcast(q[3].s3, 2), acc[3]); acc[4] = fma(kv.s2, sub_group_broadcast(q[4].s3, 2), acc[4]); acc[5] = fma(kv.s2, sub_group_broadcast(q[5].s3, 2), acc[5]); acc[6] = fma(kv.s2, sub_group_broadcast(q[6].s3, 2), acc[6]); acc[7] = fma(kv.s2, sub_group_broadcast(q[7].s3, 2), acc[7]);
            acc[0] = fma(kv.s3, sub_group_broadcast(q[0].s3, 3), acc[0]); acc[1] = fma(kv.s3, sub_group_broadcast(q[1].s3, 3), acc[1]); acc[2] = fma(kv.s3, sub_group_broadcast(q[2].s3, 3), acc[2]); acc[3] = fma(kv.s3, sub_group_broadcast(q[3].s3, 3), acc[3]); acc[4] = fma(kv.s3, sub_group_broadcast(q[4].s3, 3), acc[4]); acc[5] = fma(kv.s3, sub_group_broadcast(q[5].s3, 3), acc[5]); acc[6] = fma(kv.s3, sub_group_broadcast(q[6].s3, 3), acc[6]); acc[7] = fma(kv.s3, sub_group_broadcast(q[7].s3, 3), acc[7]);
            acc[0] = fma(kv.s4, sub_group_broadcast(q[0].s3, 4), acc[0]); acc[1] = fma(kv.s4, sub_group_broadcast(q[1].s3, 4), acc[1]); acc[2] = fma(kv.s4, sub_group_broadcast(q[2].s3, 4), acc[2]); acc[3] = fma(kv.s4, sub_group_broadcast(q[3].s3, 4), acc[3]); acc[4] = fma(kv.s4, sub_group_broadcast(q[4].s3, 4), acc[4]); acc[5] = fma(kv.s4, sub_group_broadcast(q[5].s3, 4), acc[5]); acc[6] = fma(kv.s4, sub_group_broadcast(q[6].s3, 4), acc[6]); acc[7] = fma(kv.s4, sub_group_broadcast(q[7].s3, 4), acc[7]);
            acc[0] = fma(kv.s5, sub_group_broadcast(q[0].s3, 5), acc[0]); acc[1] = fma(kv.s5, sub_group_broadcast(q[1].s3, 5), acc[1]); acc[2] = fma(kv.s5, sub_group_broadcast(q[2].s3, 5), acc[2]); acc[3] = fma(kv.s5, sub_group_broadcast(q[3].s3, 5), acc[3]); acc[4] = fma(kv.s5, sub_group_broadcast(q[4].s3, 5), acc[4]); acc[5] = fma(kv.s5, sub_group_broadcast(q[5].s3, 5), acc[5]); acc[6] = fma(kv.s5, sub_group_broadcast(q[6].s3, 5), acc[6]); acc[7] = fma(kv.s5, sub_group_broadcast(q[7].s3, 5), acc[7]);
            acc[0] = fma(kv.s6, sub_group_broadcast(q[0].s3, 6), acc[0]); acc[1] = fma(kv.s6, sub_group_broadcast(q[1].s3, 6), acc[1]); acc[2] = fma(kv.s6, sub_group_broadcast(q[2].s3, 6), acc[2]); acc[3] = fma(kv.s6, sub_group_broadcast(q[3].s3, 6), acc[3]); acc[4] = fma(kv.s6, sub_group_broadcast(q[4].s3, 6), acc[4]); acc[5] = fma(kv.s6, sub_group_broadcast(q[5].s3, 6), acc[5]); acc[6] = fma(kv.s6, sub_group_broadcast(q[6].s3, 6), acc[6]); acc[7] = fma(kv.s6, sub_group_broadcast(q[7].s3, 6), acc[7]);
            acc[0] = fma(kv.s7, sub_group_broadcast(q[0].s3, 7), acc[0]); acc[1] = fma(kv.s7, sub_group_broadcast(q[1].s3, 7), acc[1]); acc[2] = fma(kv.s7, sub_group_broadcast(q[2].s3, 7), acc[2]); acc[3] = fma(kv.s7, sub_group_broadcast(q[3].s3, 7), acc[3]); acc[4] = fma(kv.s7, sub_group_broadcast(q[4].s3, 7), acc[4]); acc[5] = fma(kv.s7, sub_group_broadcast(q[5].s3, 7), acc[5]); acc[6] = fma(kv.s7, sub_group_broadcast(q[6].s3, 7), acc[6]); acc[7] = fma(kv.s7, sub_group_broadcast(q[7].s3, 7), acc[7]);
            kv = vload_half8(0, kr + t * 64 + 32);
            acc[0] = fma(kv.s0, sub_group_broadcast(q[0].s4, 0), acc[0]); acc[1] = fma(kv.s0, sub_group_broadcast(q[1].s4, 0), acc[1]); acc[2] = fma(kv.s0, sub_group_broadcast(q[2].s4, 0), acc[2]); acc[3] = fma(kv.s0, sub_group_broadcast(q[3].s4, 0), acc[3]); acc[4] = fma(kv.s0, sub_group_broadcast(q[4].s4, 0), acc[4]); acc[5] = fma(kv.s0, sub_group_broadcast(q[5].s4, 0), acc[5]); acc[6] = fma(kv.s0, sub_group_broadcast(q[6].s4, 0), acc[6]); acc[7] = fma(kv.s0, sub_group_broadcast(q[7].s4, 0), acc[7]);
            acc[0] = fma(kv.s1, sub_group_broadcast(q[0].s4, 1), acc[0]); acc[1] = fma(kv.s1, sub_group_broadcast(q[1].s4, 1), acc[1]); acc[2] = fma(kv.s1, sub_group_broadcast(q[2].s4, 1), acc[2]); acc[3] = fma(kv.s1, sub_group_broadcast(q[3].s4, 1), acc[3]); acc[4] = fma(kv.s1, sub_group_broadcast(q[4].s4, 1), acc[4]); acc[5] = fma(kv.s1, sub_group_broadcast(q[5].s4, 1), acc[5]); acc[6] = fma(kv.s1, sub_group_broadcast(q[6].s4, 1), acc[6]); acc[7] = fma(kv.s1, sub_group_broadcast(q[7].s4, 1), acc[7]);
            acc[0] = fma(kv.s2, sub_group_broadcast(q[0].s4, 2), acc[0]); acc[1] = fma(kv.s2, sub_group_broadcast(q[1].s4, 2), acc[1]); acc[2] = fma(kv.s2, sub_group_broadcast(q[2].s4, 2), acc[2]); acc[3] = fma(kv.s2, sub_group_broadcast(q[3].s4, 2), acc[3]); acc[4] = fma(kv.s2, sub_group_broadcast(q[4].s4, 2), acc[4]); acc[5] = fma(kv.s2, sub_group_broadcast(q[5].s4, 2), acc[5]); acc[6] = fma(kv.s2, sub_group_broadcast(q[6].s4, 2), acc[6]); acc[7] = fma(kv.s2, sub_group_broadcast(q[7].s4, 2), acc[7]);
            acc[0] = fma(kv.s3, sub_group_broadcast(q[0].s4, 3), acc[0]); acc[1] = fma(kv.s3, sub_group_broadcast(q[1].s4, 3), acc[1]); acc[2] = fma(kv.s3, sub_group_broadcast(q[2].s4, 3), acc[2]); acc[3] = fma(kv.s3, sub_group_broadcast(q[3].s4, 3), acc[3]); acc[4] = fma(kv.s3, sub_group_broadcast(q[4].s4, 3), acc[4]); acc[5] = fma(kv.s3, sub_group_broadcast(q[5].s4, 3), acc[5]); acc[6] = fma(kv.s3, sub_group_broadcast(q[6].s4, 3), acc[6]); acc[7] = fma(kv.s3, sub_group_broadcast(q[7].s4, 3), acc[7]);
            acc[0] = fma(kv.s4, sub_group_broadcast(q[0].s4, 4), acc[0]); acc[1] = fma(kv.s4, sub_group_broadcast(q[1].s4, 4), acc[1]); acc[2] = fma(kv.s4, sub_group_broadcast(q[2].s4, 4), acc[2]); acc[3] = fma(kv.s4, sub_group_broadcast(q[3].s4, 4), acc[3]); acc[4] = fma(kv.s4, sub_group_broadcast(q[4].s4, 4), acc[4]); acc[5] = fma(kv.s4, sub_group_broadcast(q[5].s4, 4), acc[5]); acc[6] = fma(kv.s4, sub_group_broadcast(q[6].s4, 4), acc[6]); acc[7] = fma(kv.s4, sub_group_broadcast(q[7].s4, 4), acc[7]);
            acc[0] = fma(kv.s5, sub_group_broadcast(q[0].s4, 5), acc[0]); acc[1] = fma(kv.s5, sub_group_broadcast(q[1].s4, 5), acc[1]); acc[2] = fma(kv.s5, sub_group_broadcast(q[2].s4, 5), acc[2]); acc[3] = fma(kv.s5, sub_group_broadcast(q[3].s4, 5), acc[3]); acc[4] = fma(kv.s5, sub_group_broadcast(q[4].s4, 5), acc[4]); acc[5] = fma(kv.s5, sub_group_broadcast(q[5].s4, 5), acc[5]); acc[6] = fma(kv.s5, sub_group_broadcast(q[6].s4, 5), acc[6]); acc[7] = fma(kv.s5, sub_group_broadcast(q[7].s4, 5), acc[7]);
            acc[0] = fma(kv.s6, sub_group_broadcast(q[0].s4, 6), acc[0]); acc[1] = fma(kv.s6, sub_group_broadcast(q[1].s4, 6), acc[1]); acc[2] = fma(kv.s6, sub_group_broadcast(q[2].s4, 6), acc[2]); acc[3] = fma(kv.s6, sub_group_broadcast(q[3].s4, 6), acc[3]); acc[4] = fma(kv.s6, sub_group_broadcast(q[4].s4, 6), acc[4]); acc[5] = fma(kv.s6, sub_group_broadcast(q[5].s4, 6), acc[5]); acc[6] = fma(kv.s6, sub_group_broadcast(q[6].s4, 6), acc[6]); acc[7] = fma(kv.s6, sub_group_broadcast(q[7].s4, 6), acc[7]);
            acc[0] = fma(kv.s7, sub_group_broadcast(q[0].s4, 7), acc[0]); acc[1] = fma(kv.s7, sub_group_broadcast(q[1].s4, 7), acc[1]); acc[2] = fma(kv.s7, sub_group_broadcast(q[2].s4, 7), acc[2]); acc[3] = fma(kv.s7, sub_group_broadcast(q[3].s4, 7), acc[3]); acc[4] = fma(kv.s7, sub_group_broadcast(q[4].s4, 7), acc[4]); acc[5] = fma(kv.s7, sub_group_broadcast(q[5].s4, 7), acc[5]); acc[6] = fma(kv.s7, sub_group_broadcast(q[6].s4, 7), acc[6]); acc[7] = fma(kv.s7, sub_group_broadcast(q[7].s4, 7), acc[7]);
            kv = vload_half8(0, kr + t * 64 + 40);
            acc[0] = fma(kv.s0, sub_group_broadcast(q[0].s5, 0), acc[0]); acc[1] = fma(kv.s0, sub_group_broadcast(q[1].s5, 0), acc[1]); acc[2] = fma(kv.s0, sub_group_broadcast(q[2].s5, 0), acc[2]); acc[3] = fma(kv.s0, sub_group_broadcast(q[3].s5, 0), acc[3]); acc[4] = fma(kv.s0, sub_group_broadcast(q[4].s5, 0), acc[4]); acc[5] = fma(kv.s0, sub_group_broadcast(q[5].s5, 0), acc[5]); acc[6] = fma(kv.s0, sub_group_broadcast(q[6].s5, 0), acc[6]); acc[7] = fma(kv.s0, sub_group_broadcast(q[7].s5, 0), acc[7]);
            acc[0] = fma(kv.s1, sub_group_broadcast(q[0].s5, 1), acc[0]); acc[1] = fma(kv.s1, sub_group_broadcast(q[1].s5, 1), acc[1]); acc[2] = fma(kv.s1, sub_group_broadcast(q[2].s5, 1), acc[2]); acc[3] = fma(kv.s1, sub_group_broadcast(q[3].s5, 1), acc[3]); acc[4] = fma(kv.s1, sub_group_broadcast(q[4].s5, 1), acc[4]); acc[5] = fma(kv.s1, sub_group_broadcast(q[5].s5, 1), acc[5]); acc[6] = fma(kv.s1, sub_group_broadcast(q[6].s5, 1), acc[6]); acc[7] = fma(kv.s1, sub_group_broadcast(q[7].s5, 1), acc[7]);
            acc[0] = fma(kv.s2, sub_group_broadcast(q[0].s5, 2), acc[0]); acc[1] = fma(kv.s2, sub_group_broadcast(q[1].s5, 2), acc[1]); acc[2] = fma(kv.s2, sub_group_broadcast(q[2].s5, 2), acc[2]); acc[3] = fma(kv.s2, sub_group_broadcast(q[3].s5, 2), acc[3]); acc[4] = fma(kv.s2, sub_group_broadcast(q[4].s5, 2), acc[4]); acc[5] = fma(kv.s2, sub_group_broadcast(q[5].s5, 2), acc[5]); acc[6] = fma(kv.s2, sub_group_broadcast(q[6].s5, 2), acc[6]); acc[7] = fma(kv.s2, sub_group_broadcast(q[7].s5, 2), acc[7]);
            acc[0] = fma(kv.s3, sub_group_broadcast(q[0].s5, 3), acc[0]); acc[1] = fma(kv.s3, sub_group_broadcast(q[1].s5, 3), acc[1]); acc[2] = fma(kv.s3, sub_group_broadcast(q[2].s5, 3), acc[2]); acc[3] = fma(kv.s3, sub_group_broadcast(q[3].s5, 3), acc[3]); acc[4] = fma(kv.s3, sub_group_broadcast(q[4].s5, 3), acc[4]); acc[5] = fma(kv.s3, sub_group_broadcast(q[5].s5, 3), acc[5]); acc[6] = fma(kv.s3, sub_group_broadcast(q[6].s5, 3), acc[6]); acc[7] = fma(kv.s3, sub_group_broadcast(q[7].s5, 3), acc[7]);
            acc[0] = fma(kv.s4, sub_group_broadcast(q[0].s5, 4), acc[0]); acc[1] = fma(kv.s4, sub_group_broadcast(q[1].s5, 4), acc[1]); acc[2] = fma(kv.s4, sub_group_broadcast(q[2].s5, 4), acc[2]); acc[3] = fma(kv.s4, sub_group_broadcast(q[3].s5, 4), acc[3]); acc[4] = fma(kv.s4, sub_group_broadcast(q[4].s5, 4), acc[4]); acc[5] = fma(kv.s4, sub_group_broadcast(q[5].s5, 4), acc[5]); acc[6] = fma(kv.s4, sub_group_broadcast(q[6].s5, 4), acc[6]); acc[7] = fma(kv.s4, sub_group_broadcast(q[7].s5, 4), acc[7]);
            acc[0] = fma(kv.s5, sub_group_broadcast(q[0].s5, 5), acc[0]); acc[1] = fma(kv.s5, sub_group_broadcast(q[1].s5, 5), acc[1]); acc[2] = fma(kv.s5, sub_group_broadcast(q[2].s5, 5), acc[2]); acc[3] = fma(kv.s5, sub_group_broadcast(q[3].s5, 5), acc[3]); acc[4] = fma(kv.s5, sub_group_broadcast(q[4].s5, 5), acc[4]); acc[5] = fma(kv.s5, sub_group_broadcast(q[5].s5, 5), acc[5]); acc[6] = fma(kv.s5, sub_group_broadcast(q[6].s5, 5), acc[6]); acc[7] = fma(kv.s5, sub_group_broadcast(q[7].s5, 5), acc[7]);
            acc[0] = fma(kv.s6, sub_group_broadcast(q[0].s5, 6), acc[0]); acc[1] = fma(kv.s6, sub_group_broadcast(q[1].s5, 6), acc[1]); acc[2] = fma(kv.s6, sub_group_broadcast(q[2].s5, 6), acc[2]); acc[3] = fma(kv.s6, sub_group_broadcast(q[3].s5, 6), acc[3]); acc[4] = fma(kv.s6, sub_group_broadcast(q[4].s5, 6), acc[4]); acc[5] = fma(kv.s6, sub_group_broadcast(q[5].s5, 6), acc[5]); acc[6] = fma(kv.s6, sub_group_broadcast(q[6].s5, 6), acc[6]); acc[7] = fma(kv.s6, sub_group_broadcast(q[7].s5, 6), acc[7]);
            acc[0] = fma(kv.s7, sub_group_broadcast(q[0].s5, 7), acc[0]); acc[1] = fma(kv.s7, sub_group_broadcast(q[1].s5, 7), acc[1]); acc[2] = fma(kv.s7, sub_group_broadcast(q[2].s5, 7), acc[2]); acc[3] = fma(kv.s7, sub_group_broadcast(q[3].s5, 7), acc[3]); acc[4] = fma(kv.s7, sub_group_broadcast(q[4].s5, 7), acc[4]); acc[5] = fma(kv.s7, sub_group_broadcast(q[5].s5, 7), acc[5]); acc[6] = fma(kv.s7, sub_group_broadcast(q[6].s5, 7), acc[6]); acc[7] = fma(kv.s7, sub_group_broadcast(q[7].s5, 7), acc[7]);
            kv = vload_half8(0, kr + t * 64 + 48);
            acc[0] = fma(kv.s0, sub_group_broadcast(q[0].s6, 0), acc[0]); acc[1] = fma(kv.s0, sub_group_broadcast(q[1].s6, 0), acc[1]); acc[2] = fma(kv.s0, sub_group_broadcast(q[2].s6, 0), acc[2]); acc[3] = fma(kv.s0, sub_group_broadcast(q[3].s6, 0), acc[3]); acc[4] = fma(kv.s0, sub_group_broadcast(q[4].s6, 0), acc[4]); acc[5] = fma(kv.s0, sub_group_broadcast(q[5].s6, 0), acc[5]); acc[6] = fma(kv.s0, sub_group_broadcast(q[6].s6, 0), acc[6]); acc[7] = fma(kv.s0, sub_group_broadcast(q[7].s6, 0), acc[7]);
            acc[0] = fma(kv.s1, sub_group_broadcast(q[0].s6, 1), acc[0]); acc[1] = fma(kv.s1, sub_group_broadcast(q[1].s6, 1), acc[1]); acc[2] = fma(kv.s1, sub_group_broadcast(q[2].s6, 1), acc[2]); acc[3] = fma(kv.s1, sub_group_broadcast(q[3].s6, 1), acc[3]); acc[4] = fma(kv.s1, sub_group_broadcast(q[4].s6, 1), acc[4]); acc[5] = fma(kv.s1, sub_group_broadcast(q[5].s6, 1), acc[5]); acc[6] = fma(kv.s1, sub_group_broadcast(q[6].s6, 1), acc[6]); acc[7] = fma(kv.s1, sub_group_broadcast(q[7].s6, 1), acc[7]);
            acc[0] = fma(kv.s2, sub_group_broadcast(q[0].s6, 2), acc[0]); acc[1] = fma(kv.s2, sub_group_broadcast(q[1].s6, 2), acc[1]); acc[2] = fma(kv.s2, sub_group_broadcast(q[2].s6, 2), acc[2]); acc[3] = fma(kv.s2, sub_group_broadcast(q[3].s6, 2), acc[3]); acc[4] = fma(kv.s2, sub_group_broadcast(q[4].s6, 2), acc[4]); acc[5] = fma(kv.s2, sub_group_broadcast(q[5].s6, 2), acc[5]); acc[6] = fma(kv.s2, sub_group_broadcast(q[6].s6, 2), acc[6]); acc[7] = fma(kv.s2, sub_group_broadcast(q[7].s6, 2), acc[7]);
            acc[0] = fma(kv.s3, sub_group_broadcast(q[0].s6, 3), acc[0]); acc[1] = fma(kv.s3, sub_group_broadcast(q[1].s6, 3), acc[1]); acc[2] = fma(kv.s3, sub_group_broadcast(q[2].s6, 3), acc[2]); acc[3] = fma(kv.s3, sub_group_broadcast(q[3].s6, 3), acc[3]); acc[4] = fma(kv.s3, sub_group_broadcast(q[4].s6, 3), acc[4]); acc[5] = fma(kv.s3, sub_group_broadcast(q[5].s6, 3), acc[5]); acc[6] = fma(kv.s3, sub_group_broadcast(q[6].s6, 3), acc[6]); acc[7] = fma(kv.s3, sub_group_broadcast(q[7].s6, 3), acc[7]);
            acc[0] = fma(kv.s4, sub_group_broadcast(q[0].s6, 4), acc[0]); acc[1] = fma(kv.s4, sub_group_broadcast(q[1].s6, 4), acc[1]); acc[2] = fma(kv.s4, sub_group_broadcast(q[2].s6, 4), acc[2]); acc[3] = fma(kv.s4, sub_group_broadcast(q[3].s6, 4), acc[3]); acc[4] = fma(kv.s4, sub_group_broadcast(q[4].s6, 4), acc[4]); acc[5] = fma(kv.s4, sub_group_broadcast(q[5].s6, 4), acc[5]); acc[6] = fma(kv.s4, sub_group_broadcast(q[6].s6, 4), acc[6]); acc[7] = fma(kv.s4, sub_group_broadcast(q[7].s6, 4), acc[7]);
            acc[0] = fma(kv.s5, sub_group_broadcast(q[0].s6, 5), acc[0]); acc[1] = fma(kv.s5, sub_group_broadcast(q[1].s6, 5), acc[1]); acc[2] = fma(kv.s5, sub_group_broadcast(q[2].s6, 5), acc[2]); acc[3] = fma(kv.s5, sub_group_broadcast(q[3].s6, 5), acc[3]); acc[4] = fma(kv.s5, sub_group_broadcast(q[4].s6, 5), acc[4]); acc[5] = fma(kv.s5, sub_group_broadcast(q[5].s6, 5), acc[5]); acc[6] = fma(kv.s5, sub_group_broadcast(q[6].s6, 5), acc[6]); acc[7] = fma(kv.s5, sub_group_broadcast(q[7].s6, 5), acc[7]);
            acc[0] = fma(kv.s6, sub_group_broadcast(q[0].s6, 6), acc[0]); acc[1] = fma(kv.s6, sub_group_broadcast(q[1].s6, 6), acc[1]); acc[2] = fma(kv.s6, sub_group_broadcast(q[2].s6, 6), acc[2]); acc[3] = fma(kv.s6, sub_group_broadcast(q[3].s6, 6), acc[3]); acc[4] = fma(kv.s6, sub_group_broadcast(q[4].s6, 6), acc[4]); acc[5] = fma(kv.s6, sub_group_broadcast(q[5].s6, 6), acc[5]); acc[6] = fma(kv.s6, sub_group_broadcast(q[6].s6, 6), acc[6]); acc[7] = fma(kv.s6, sub_group_broadcast(q[7].s6, 6), acc[7]);
            acc[0] = fma(kv.s7, sub_group_broadcast(q[0].s6, 7), acc[0]); acc[1] = fma(kv.s7, sub_group_broadcast(q[1].s6, 7), acc[1]); acc[2] = fma(kv.s7, sub_group_broadcast(q[2].s6, 7), acc[2]); acc[3] = fma(kv.s7, sub_group_broadcast(q[3].s6, 7), acc[3]); acc[4] = fma(kv.s7, sub_group_broadcast(q[4].s6, 7), acc[4]); acc[5] = fma(kv.s7, sub_group_broadcast(q[5].s6, 7), acc[5]); acc[6] = fma(kv.s7, sub_group_broadcast(q[6].s6, 7), acc[6]); acc[7] = fma(kv.s7, sub_group_broadcast(q[7].s6, 7), acc[7]);
            kv = vload_half8(0, kr + t * 64 + 56);
            acc[0] = fma(kv.s0, sub_group_broadcast(q[0].s7, 0), acc[0]); acc[1] = fma(kv.s0, sub_group_broadcast(q[1].s7, 0), acc[1]); acc[2] = fma(kv.s0, sub_group_broadcast(q[2].s7, 0), acc[2]); acc[3] = fma(kv.s0, sub_group_broadcast(q[3].s7, 0), acc[3]); acc[4] = fma(kv.s0, sub_group_broadcast(q[4].s7, 0), acc[4]); acc[5] = fma(kv.s0, sub_group_broadcast(q[5].s7, 0), acc[5]); acc[6] = fma(kv.s0, sub_group_broadcast(q[6].s7, 0), acc[6]); acc[7] = fma(kv.s0, sub_group_broadcast(q[7].s7, 0), acc[7]);
            acc[0] = fma(kv.s1, sub_group_broadcast(q[0].s7, 1), acc[0]); acc[1] = fma(kv.s1, sub_group_broadcast(q[1].s7, 1), acc[1]); acc[2] = fma(kv.s1, sub_group_broadcast(q[2].s7, 1), acc[2]); acc[3] = fma(kv.s1, sub_group_broadcast(q[3].s7, 1), acc[3]); acc[4] = fma(kv.s1, sub_group_broadcast(q[4].s7, 1), acc[4]); acc[5] = fma(kv.s1, sub_group_broadcast(q[5].s7, 1), acc[5]); acc[6] = fma(kv.s1, sub_group_broadcast(q[6].s7, 1), acc[6]); acc[7] = fma(kv.s1, sub_group_broadcast(q[7].s7, 1), acc[7]);
            acc[0] = fma(kv.s2, sub_group_broadcast(q[0].s7, 2), acc[0]); acc[1] = fma(kv.s2, sub_group_broadcast(q[1].s7, 2), acc[1]); acc[2] = fma(kv.s2, sub_group_broadcast(q[2].s7, 2), acc[2]); acc[3] = fma(kv.s2, sub_group_broadcast(q[3].s7, 2), acc[3]); acc[4] = fma(kv.s2, sub_group_broadcast(q[4].s7, 2), acc[4]); acc[5] = fma(kv.s2, sub_group_broadcast(q[5].s7, 2), acc[5]); acc[6] = fma(kv.s2, sub_group_broadcast(q[6].s7, 2), acc[6]); acc[7] = fma(kv.s2, sub_group_broadcast(q[7].s7, 2), acc[7]);
            acc[0] = fma(kv.s3, sub_group_broadcast(q[0].s7, 3), acc[0]); acc[1] = fma(kv.s3, sub_group_broadcast(q[1].s7, 3), acc[1]); acc[2] = fma(kv.s3, sub_group_broadcast(q[2].s7, 3), acc[2]); acc[3] = fma(kv.s3, sub_group_broadcast(q[3].s7, 3), acc[3]); acc[4] = fma(kv.s3, sub_group_broadcast(q[4].s7, 3), acc[4]); acc[5] = fma(kv.s3, sub_group_broadcast(q[5].s7, 3), acc[5]); acc[6] = fma(kv.s3, sub_group_broadcast(q[6].s7, 3), acc[6]); acc[7] = fma(kv.s3, sub_group_broadcast(q[7].s7, 3), acc[7]);
            acc[0] = fma(kv.s4, sub_group_broadcast(q[0].s7, 4), acc[0]); acc[1] = fma(kv.s4, sub_group_broadcast(q[1].s7, 4), acc[1]); acc[2] = fma(kv.s4, sub_group_broadcast(q[2].s7, 4), acc[2]); acc[3] = fma(kv.s4, sub_group_broadcast(q[3].s7, 4), acc[3]); acc[4] = fma(kv.s4, sub_group_broadcast(q[4].s7, 4), acc[4]); acc[5] = fma(kv.s4, sub_group_broadcast(q[5].s7, 4), acc[5]); acc[6] = fma(kv.s4, sub_group_broadcast(q[6].s7, 4), acc[6]); acc[7] = fma(kv.s4, sub_group_broadcast(q[7].s7, 4), acc[7]);
            acc[0] = fma(kv.s5, sub_group_broadcast(q[0].s7, 5), acc[0]); acc[1] = fma(kv.s5, sub_group_broadcast(q[1].s7, 5), acc[1]); acc[2] = fma(kv.s5, sub_group_broadcast(q[2].s7, 5), acc[2]); acc[3] = fma(kv.s5, sub_group_broadcast(q[3].s7, 5), acc[3]); acc[4] = fma(kv.s5, sub_group_broadcast(q[4].s7, 5), acc[4]); acc[5] = fma(kv.s5, sub_group_broadcast(q[5].s7, 5), acc[5]); acc[6] = fma(kv.s5, sub_group_broadcast(q[6].s7, 5), acc[6]); acc[7] = fma(kv.s5, sub_group_broadcast(q[7].s7, 5), acc[7]);
            acc[0] = fma(kv.s6, sub_group_broadcast(q[0].s7, 6), acc[0]); acc[1] = fma(kv.s6, sub_group_broadcast(q[1].s7, 6), acc[1]); acc[2] = fma(kv.s6, sub_group_broadcast(q[2].s7, 6), acc[2]); acc[3] = fma(kv.s6, sub_group_broadcast(q[3].s7, 6), acc[3]); acc[4] = fma(kv.s6, sub_group_broadcast(q[4].s7, 6), acc[4]); acc[5] = fma(kv.s6, sub_group_broadcast(q[5].s7, 6), acc[5]); acc[6] = fma(kv.s6, sub_group_broadcast(q[6].s7, 6), acc[6]); acc[7] = fma(kv.s6, sub_group_broadcast(q[7].s7, 6), acc[7]);
            acc[0] = fma(kv.s7, sub_group_broadcast(q[0].s7, 7), acc[0]); acc[1] = fma(kv.s7, sub_group_broadcast(q[1].s7, 7), acc[1]); acc[2] = fma(kv.s7, sub_group_broadcast(q[2].s7, 7), acc[2]); acc[3] = fma(kv.s7, sub_group_broadcast(q[3].s7, 7), acc[3]); acc[4] = fma(kv.s7, sub_group_broadcast(q[4].s7, 7), acc[4]); acc[5] = fma(kv.s7, sub_group_broadcast(q[5].s7, 7), acc[5]); acc[6] = fma(kv.s7, sub_group_broadcast(q[6].s7, 7), acc[6]); acc[7] = fma(kv.s7, sub_group_broadcast(q[7].s7, 7), acc[7]);
        }
        const float mv = (live && mask) ? vload_half(r, mask) : 0.0f;
        for (int h = 0; h < H; h++) P[h][rl] = live ? acc[h] * scale + mv : -INFINITY;
    }
    barrier(CLK_LOCAL_MEM_FENCE);
    // 2) softmax statistics: subgroup sg handles head sg
    {
        const int h = sg;
        float m = -INFINITY;
        for (int i = lane; i < ch; i += 8) m = fmax(m, P[h][i]);
        m = sub_group_reduce_max(m);
        float s = 0.0f;
        for (int i = lane; i < ch; i += 8) { const float e = m == -INFINITY ? 0.0f : exp(P[h][i] - m); P[h][i] = e; s += e; }
        s = sub_group_reduce_add(s);
        if (lane == 0) { Ml[h] = m; Sl[h] = s; }
    }
    barrier(CLK_LOCAL_MEM_FENCE);
    // 3) V: lane owns 8 output dims; weights for 8 rows loaded at once, handed out by broadcast
    const int nr = min(ch, n_kv - r0);
    float8 o[H];
    for (int h = 0; h < H; h++) o[h] = (float8) 0.0f;
    for (int rr = 0; rr < nr; rr += 8) {
        float p[H];
        for (int h = 0; h < H; h++) p[h] = (rr + lane < nr) ? P[h][rr + lane] : 0.0f;
        const int nj = min(8, nr - rr);
        __global const half * vb = V + (size_t) (r0 + rr) * v_stride + lid * 8;
        if (0 < nj) { const float8 vv = vload_half8(0, vb + 0 * v_stride); o[0] = fma((float8) sub_group_broadcast(p[0], 0), vv, o[0]); o[1] = fma((float8) sub_group_broadcast(p[1], 0), vv, o[1]); o[2] = fma((float8) sub_group_broadcast(p[2], 0), vv, o[2]); o[3] = fma((float8) sub_group_broadcast(p[3], 0), vv, o[3]); o[4] = fma((float8) sub_group_broadcast(p[4], 0), vv, o[4]); o[5] = fma((float8) sub_group_broadcast(p[5], 0), vv, o[5]); o[6] = fma((float8) sub_group_broadcast(p[6], 0), vv, o[6]); o[7] = fma((float8) sub_group_broadcast(p[7], 0), vv, o[7]); }
        if (1 < nj) { const float8 vv = vload_half8(0, vb + 1 * v_stride); o[0] = fma((float8) sub_group_broadcast(p[0], 1), vv, o[0]); o[1] = fma((float8) sub_group_broadcast(p[1], 1), vv, o[1]); o[2] = fma((float8) sub_group_broadcast(p[2], 1), vv, o[2]); o[3] = fma((float8) sub_group_broadcast(p[3], 1), vv, o[3]); o[4] = fma((float8) sub_group_broadcast(p[4], 1), vv, o[4]); o[5] = fma((float8) sub_group_broadcast(p[5], 1), vv, o[5]); o[6] = fma((float8) sub_group_broadcast(p[6], 1), vv, o[6]); o[7] = fma((float8) sub_group_broadcast(p[7], 1), vv, o[7]); }
        if (2 < nj) { const float8 vv = vload_half8(0, vb + 2 * v_stride); o[0] = fma((float8) sub_group_broadcast(p[0], 2), vv, o[0]); o[1] = fma((float8) sub_group_broadcast(p[1], 2), vv, o[1]); o[2] = fma((float8) sub_group_broadcast(p[2], 2), vv, o[2]); o[3] = fma((float8) sub_group_broadcast(p[3], 2), vv, o[3]); o[4] = fma((float8) sub_group_broadcast(p[4], 2), vv, o[4]); o[5] = fma((float8) sub_group_broadcast(p[5], 2), vv, o[5]); o[6] = fma((float8) sub_group_broadcast(p[6], 2), vv, o[6]); o[7] = fma((float8) sub_group_broadcast(p[7], 2), vv, o[7]); }
        if (3 < nj) { const float8 vv = vload_half8(0, vb + 3 * v_stride); o[0] = fma((float8) sub_group_broadcast(p[0], 3), vv, o[0]); o[1] = fma((float8) sub_group_broadcast(p[1], 3), vv, o[1]); o[2] = fma((float8) sub_group_broadcast(p[2], 3), vv, o[2]); o[3] = fma((float8) sub_group_broadcast(p[3], 3), vv, o[3]); o[4] = fma((float8) sub_group_broadcast(p[4], 3), vv, o[4]); o[5] = fma((float8) sub_group_broadcast(p[5], 3), vv, o[5]); o[6] = fma((float8) sub_group_broadcast(p[6], 3), vv, o[6]); o[7] = fma((float8) sub_group_broadcast(p[7], 3), vv, o[7]); }
        if (4 < nj) { const float8 vv = vload_half8(0, vb + 4 * v_stride); o[0] = fma((float8) sub_group_broadcast(p[0], 4), vv, o[0]); o[1] = fma((float8) sub_group_broadcast(p[1], 4), vv, o[1]); o[2] = fma((float8) sub_group_broadcast(p[2], 4), vv, o[2]); o[3] = fma((float8) sub_group_broadcast(p[3], 4), vv, o[3]); o[4] = fma((float8) sub_group_broadcast(p[4], 4), vv, o[4]); o[5] = fma((float8) sub_group_broadcast(p[5], 4), vv, o[5]); o[6] = fma((float8) sub_group_broadcast(p[6], 4), vv, o[6]); o[7] = fma((float8) sub_group_broadcast(p[7], 4), vv, o[7]); }
        if (5 < nj) { const float8 vv = vload_half8(0, vb + 5 * v_stride); o[0] = fma((float8) sub_group_broadcast(p[0], 5), vv, o[0]); o[1] = fma((float8) sub_group_broadcast(p[1], 5), vv, o[1]); o[2] = fma((float8) sub_group_broadcast(p[2], 5), vv, o[2]); o[3] = fma((float8) sub_group_broadcast(p[3], 5), vv, o[3]); o[4] = fma((float8) sub_group_broadcast(p[4], 5), vv, o[4]); o[5] = fma((float8) sub_group_broadcast(p[5], 5), vv, o[5]); o[6] = fma((float8) sub_group_broadcast(p[6], 5), vv, o[6]); o[7] = fma((float8) sub_group_broadcast(p[7], 5), vv, o[7]); }
        if (6 < nj) { const float8 vv = vload_half8(0, vb + 6 * v_stride); o[0] = fma((float8) sub_group_broadcast(p[0], 6), vv, o[0]); o[1] = fma((float8) sub_group_broadcast(p[1], 6), vv, o[1]); o[2] = fma((float8) sub_group_broadcast(p[2], 6), vv, o[2]); o[3] = fma((float8) sub_group_broadcast(p[3], 6), vv, o[3]); o[4] = fma((float8) sub_group_broadcast(p[4], 6), vv, o[4]); o[5] = fma((float8) sub_group_broadcast(p[5], 6), vv, o[5]); o[6] = fma((float8) sub_group_broadcast(p[6], 6), vv, o[6]); o[7] = fma((float8) sub_group_broadcast(p[7], 6), vv, o[7]); }
        if (7 < nj) { const float8 vv = vload_half8(0, vb + 7 * v_stride); o[0] = fma((float8) sub_group_broadcast(p[0], 7), vv, o[0]); o[1] = fma((float8) sub_group_broadcast(p[1], 7), vv, o[1]); o[2] = fma((float8) sub_group_broadcast(p[2], 7), vv, o[2]); o[3] = fma((float8) sub_group_broadcast(p[3], 7), vv, o[3]); o[4] = fma((float8) sub_group_broadcast(p[4], 7), vv, o[4]); o[5] = fma((float8) sub_group_broadcast(p[5], 7), vv, o[5]); o[6] = fma((float8) sub_group_broadcast(p[6], 7), vv, o[6]); o[7] = fma((float8) sub_group_broadcast(p[7], 7), vv, o[7]); }
    }
    __global float * pc = part + (size_t) c * H * (2 + DV);
    for (int h = 0; h < H; h++) {
        if (lid == 0) { pc[h * (2 + DV)] = Ml[h]; pc[h * (2 + DV) + 1] = Sl[h]; }
        vstore8(o[h], 0, pc + h * (2 + DV) + 2 + lid * 8);
    }
}
